export interface Area {
  id: number;
  name: string;
}

export const TEST_AREAS: Area[] = [
  { id: 1, name: 'Steuern und Steuerstrafrecht' },
  { id: 2, name: 'Wirtschaftsstrafrecht' },
  { id: 3, name: 'Landwirtschaftsrecht' },
  { id: 4, name: 'Forstrecht' },
  { id: 5, name: 'Allgemeine Praxis' },
  { id: 6, name: 'Haftpflichtrecht' },
  { id: 7, name: 'Apothekenrecht' },
  { id: 8, name: 'Pharmarecht' },
  { id: 9, name: 'Arbeitsrecht' },
  { id: 10, name: 'Medizinische Haftung' },
  { id: 11, name: 'Patientenrecht' },
  { id: 12, name: 'Bank- und Kapitalmarktrecht' },
  { id: 13, name: 'Bauwesenrecht' },
  { id: 14, name: 'Bauträgerrecht' },
  { id: 15, name: 'Bauvertragsrecht' },
  { id: 16, name: 'Beamten- und Disziplinarrecht' },
  { id: 17, name: 'Bergrecht' },
  { id: 18, name: 'Berufs- und Ethikrecht' },
  { id: 19, name: 'Betriebsanlagenrecht' },
  { id: 20, name: 'Datenschutzrecht' },
  { id: 21, name: 'Domainrecht' },
  { id: 22, name: 'IT- und Softwarerecht' },
  { id: 23, name: 'Ehe- und Familienrecht' },
  { id: 24, name: 'Energierecht' },
  { id: 25, name: 'Enteignungsrecht' },
  { id: 26, name: 'Erb- und Testamentsrecht' },
  { id: 27, name: 'Erwachsenenvertretung' },
  { id: 28, name: 'Europarecht' },
  { id: 29, name: 'Fischereirecht' },
  { id: 30, name: 'Franchising' },
  { id: 31, name: 'Ausländer- und Asylrecht' },
  { id: 32, name: 'Kommunalrecht' },
  { id: 33, name: 'Gesellschaftsrecht' },
  { id: 34, name: 'Gesellschaftsgründungen' },
  { id: 35, name: 'Handelsrecht' },
  { id: 36, name: 'Industrielleigentumsrecht' },
  { id: 37, name: 'Urheber- und Markenrecht' },
  { id: 38, name: 'Handelsvertreterrecht' },
  { id: 39, name: 'Inkasso' },
  { id: 40, name: 'Vollstreckungsrecht' },
  { id: 41, name: 'Insolvenzrecht' },
  { id: 42, name: 'Unternehmenssanierung' },
  { id: 43, name: 'Internationales Recht' },
  { id: 44, name: 'Internetrecht' },
  { id: 45, name: 'Jagdrecht' },
  { id: 46, name: 'Wettbewerbsrecht' },
  { id: 47, name: 'Verbraucherschutz' },
  { id: 48, name: 'Krankenhausrecht' },
  { id: 49, name: 'Lebensmittelrecht' },
  { id: 50, name: 'Immobilien- und Grundstücksrecht' },
  { id: 51, name: 'Luftverkehrsrecht' },
  { id: 52, name: 'Mediation' },
  { id: 53, name: 'Medienrecht' },
  { id: 54, name: 'Mergers & Acquisitions' },
  { id: 55, name: 'Miet- und Wohnrecht' },
  { id: 56, name: 'Nachbarrecht' },
  { id: 57, name: 'Produkthaftung' },
  { id: 58, name: 'Raumplanung' },
  { id: 59, name: 'Reiserecht' },
  { id: 60, name: 'Schadensersatz- und Gewährleistungsrecht' },
  { id: 61, name: 'Schiedsgerichtsbarkeit' },
  { id: 62, name: 'Schiedsverfahren' },
  { id: 63, name: 'Seerecht' },
  { id: 64, name: 'Sozialrecht' },
  { id: 65, name: 'Sportrecht' },
  { id: 66, name: 'Skirecht' },
  { id: 67, name: 'Stiftungsrecht' },
  { id: 68, name: 'Strafrecht' },
  { id: 69, name: 'Telekommunikationsrecht' },
  { id: 70, name: 'Transportrecht' },
  { id: 71, name: 'Umweltrecht' },
  { id: 72, name: 'Vereinsrecht' },
  { id: 73, name: 'Verfassungsrecht' },
  { id: 74, name: 'Grundrechtsschutz' },
  { id: 75, name: 'Vergaberecht' },
  { id: 76, name: 'Verkehrsrecht' },
  { id: 77, name: 'Unfall- und Schadensrecht' },
  { id: 78, name: 'Versicherungsrecht' },
  { id: 79, name: 'Vertragsrecht' },
  { id: 80, name: 'Verwaltungsrecht' },
  { id: 81, name: 'Verwaltungsstrafrecht' },
  { id: 82, name: 'Wasserrecht' },
  { id: 83, name: 'Verteidigungsrecht' },
  { id: 84, name: 'Handelsrecht' },
  { id: 85, name: 'Wirtschaftsstrafrecht' },
  { id: 86, name: 'Wohnungseigentumsrecht' },
  { id: 87, name: 'Zivilrecht' },
  { id: 88, name: 'Zollrecht' }
];
